name: Publish .NET 8 Windows Application

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Publish .NET application
      run: dotnet publish ./PwdGen.Desktop/PwdGen.Desktop.csproj --configuration Release --runtime win-x64 --output ${{ github.workspace }}/PwdGen-win-x64 --no-self-contained -p:PublishSingleFile=true -p:PublishReadyToRun=true

    - name: Create .NET Release ZIP
      run: |
        mkdir ${{ github.workspace }}/release
        zip -j ${{ github.workspace }}/release/PwdGen-win-x64.zip ${{ github.workspace }}/PwdGen-win-x64/*

    - name: Calculate .NET ZIP SHA256
      id: sha256
      run: |
        sha256sum ${{ github.workspace }}/release/PwdGen-win-x64.zip > ${{ github.workspace }}/release/PwdGen-win-x64-sha256.txt

    - name: Gen body
      run: |
        echo "t='win-x64 SHA256 '" >> $GITHUB_ENV
        echo "sha256 = ${(cat file.txt):0:32}" >> $GITHUB_ENV
        $t$sha256 > ${{ github.workspace }}/release/body.txt
    
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.1.0
        name: v1.1.0
        body_path: ${{ github.workspace }}/release/body.txt
        draft: false
        prerelease: false
        fail_on_unmatched_files: true
        files: |
          ${{ github.workspace }}/release/PwdGen-win-x64.zip
          ${{ github.workspace }}/release/PwdGen-win-x64-sha256.txt
      env:
        GITHUB_TOKEN: ${{ secrets.Workflow }}
