name: Publish .NET 8 Windows Application

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Publish .NET application
      run: dotnet publish .\PwdGen.Desktop\PwdGen.Desktop.csproj --configuration Release --runtime win-x64 --output .\PwdGen-win-x64 --no-self-contained -p:PublishSingleFile=true -p:PublishReadyToRun=true

    - name: Create .NET Release ZIP
      run: |
        New-Item -ItemType Directory -Path ".\release"
        Compress-Archive -LiteralPath .\PwdGen-win-x64 -DestinationPath .\release\PwdGen-win-x64.zip

    - name: Calculate .NET ZIP SHA256
      id: sha256
      run: |
        Get-FileHash .\release\PwdGen-win-x64.zip > .\release\PwdGen-win-x64-sha256.txt | Format-List
    
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.1.0
        name: v1.1.0
        body_path: ./release/PwdGen-win-x64-sha256.txt
        draft: false
        prerelease: false
        fail_on_unmatched_files: true
        files: |
          ./release/PwdGen-win-x64.zip
          ./release/PwdGen-win-x64-sha256.txt
      env:
        GITHUB_TOKEN: ${{ secrets.Workflow }}
